/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
#include <stdio.h>
int main(){
    long sum=2;
    long init1=1;
    long init2=2;
    long temp;
    while (1){
        temp=init1+init2;
        if(temp>4000000){
            break;
        }
        if (temp%2==0){
            sum+=temp;
        }
        init1=init2;
        init2=temp;
        
    }
    printf("%d\n", sum);
}
